package reporter

import (
	"fmt"
	"strings"

	"github.com/bregaldahq/chaossql/internal/domain"
)

// GenerateStandalonePythonRepro generates zero-dependency standalone Python test code
// that recreates the schema, runs the minimal operations concurrently via thread workers,
// and asserts the invariant violation using standard library sqlite3.
func GenerateStandalonePythonRepro(spec domain.Spec, ops []domain.ScheduledOp, failingInv *domain.InvariantResult) string {
	var sb strings.Builder

	sb.WriteString("# Code generated by ChaosSQL (github.com/bregaldahq/chaossql). DO NOT EDIT.\n")
	sb.WriteString("# Standalone deterministic reproduction test for detected concurrency anomaly.\n")
	sb.WriteString("import concurrent.futures\n")
	sb.WriteString("import re\n")
	sb.WriteString("import sqlite3\n")
	sb.WriteString("import sys\n")
	sb.WriteString("import tempfile\n")
	sb.WriteString("import os\n\n")

	// Embedded Schema & Seed SQL
	sb.WriteString(fmt.Sprintf("SCHEMA_SQL = %q\n", strings.TrimSpace(spec.Database.Schema)))
	sb.WriteString(fmt.Sprintf("SEED_SQL = %q\n\n", strings.TrimSpace(spec.Database.Seed)))

	// Invariant configuration
	invName := "anomaly_invariant"
	invQuery := ""
	invAssert := ""
	if failingInv != nil {
		invName = failingInv.Name
		invAssert = failingInv.Expression
		for _, inv := range spec.Invariants {
			if inv.Name == failingInv.Name {
				invQuery = inv.Query
				break
			}
		}
	}
	if invQuery == "" && len(spec.Invariants) > 0 {
		invName = spec.Invariants[0].Name
		invQuery = spec.Invariants[0].Query
		invAssert = spec.Invariants[0].Assert
	}

	sb.WriteString(fmt.Sprintf("INVARIANT_NAME = %q\n", invName))
	sb.WriteString(fmt.Sprintf("INVARIANT_QUERY = %q\n", invQuery))
	sb.WriteString(fmt.Sprintf("INVARIANT_ASSERT = %q\n\n", invAssert))

	// Minimal operations list
	sb.WriteString("MINIMAL_OPS = [\n")
	for _, op := range ops {
		sb.WriteString("    {\n")
		sb.WriteString(fmt.Sprintf("        \"id\": %d,\n", op.ID))
		sb.WriteString(fmt.Sprintf("        \"name\": %q,\n", op.Name))
		sb.WriteString("        \"params\": {\n")
		for k, v := range op.Params {
			sb.WriteString(fmt.Sprintf("            %q: %q,\n", k, v))
		}
		sb.WriteString("        },\n")
		sb.WriteString("        \"steps\": [\n")
		for _, s := range op.Steps {
			sb.WriteString(fmt.Sprintf("            {\"sql\": %q, \"capture\": %q},\n", s.SQL, s.Capture))
		}
		sb.WriteString("        ],\n")
		sb.WriteString("    },\n")
	}
	sb.WriteString("]\n\n")

	// Runtime helper functions and execution harness
	sb.WriteString(`def eval_simple_arithmetic(expr: str) -> str:
    expr = expr.strip()
    if "-" in expr:
        parts = expr.split("-", 1)
        try:
            return str(int(parts[0].strip()) - int(parts[1].strip()))
        except ValueError:
            pass
    if "+" in expr:
        parts = expr.split("+", 1)
        try:
            return str(int(parts[0].strip()) + int(parts[1].strip()))
        except ValueError:
            pass
    return expr

def substitute_params(sql: str, params: dict, captures: dict) -> str:
    combined = {**(params or {}), **(captures or {})}
    pattern = re.compile(r"\{([^}]+)\}")
    def replacer(match):
        inner = match.group(1).strip()
        for k, v in combined.items():
            inner = re.sub(r"\b" + re.escape(str(k)) + r"\b", str(v), inner)
        return eval_simple_arithmetic(inner)

    res = pattern.sub(replacer, sql)
    for k, v in combined.items():
        res = re.sub(r":" + re.escape(str(k)) + r"\b", str(v), res)
    return res

def execute_op(db_path: str, op: dict) -> None:
    conn = sqlite3.connect(db_path, timeout=10.0, isolation_level=None)
    captures = {}
    try:
        cur = conn.cursor()
        for step in op.get("steps", []):
            raw_sql = step["sql"]
            sql = substitute_params(raw_sql, op.get("params", {}), captures)
            capture_var = step.get("capture")

            if capture_var:
                cur.execute(sql)
                row = cur.fetchone()
                if row is not None and len(row) > 0:
                    captures[capture_var] = row[0]
            else:
                cur.execute(sql)
    finally:
        conn.close()

def evaluate_assert(assert_expr: str, actuals: dict) -> bool:
    clean_expr = assert_expr.strip()
    try:
        return bool(eval(clean_expr, {"__builtins__": {}}, actuals))
    except Exception:
        return False

def run_repro() -> bool:
    """Runs the minimal schedule and returns True if invariant was violated (reproduced)."""
    with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as tf:
        db_path = tf.name

    try:
        conn = sqlite3.connect(db_path, isolation_level=None)
        if SCHEMA_SQL:
            conn.executescript(SCHEMA_SQL)
        if SEED_SQL:
            conn.executescript(SEED_SQL)
        conn.close()

        with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, len(MINIMAL_OPS))) as executor:
            futures = [executor.submit(execute_op, db_path, op) for op in MINIMAL_OPS]
            for f in concurrent.futures.as_completed(futures):
                f.result()  # Propagate any worker thread exceptions

        if INVARIANT_QUERY:
            conn = sqlite3.connect(db_path)
            conn.row_factory = sqlite3.Row
            cur = conn.cursor()
            cur.execute(INVARIANT_QUERY)
            row = cur.fetchone()
            actuals = dict(row) if row is not None else {}
            conn.close()

            if INVARIANT_ASSERT:
                passed = evaluate_assert(INVARIANT_ASSERT, actuals)
                if not passed:
                    print(f"🚨 [REPRODUCED] Invariant '{INVARIANT_NAME}' violated! Assert: {INVARIANT_ASSERT}, DB State: {actuals}")
                    return True
                print(f"Invariant '{INVARIANT_NAME}' satisfied: {actuals}")
                return False
        return False
    finally:
        if os.path.exists(db_path):
            try:
                os.remove(db_path)
            except OSError:
                pass

def test_anomaly_reproduction():
    """Pytest / unittest entry point."""
    violated = run_repro()
    assert violated, f"Expected concurrency anomaly for invariant '{INVARIANT_NAME}' to be reproduced"

if __name__ == "__main__":
    violation_found = run_repro()
    if violation_found:
        print(f"Success: Concurrency anomaly for '{INVARIANT_NAME}' reproduced deterministically.")
        sys.exit(0)
    else:
        print("Anomaly was not reproduced on this run.")
        sys.exit(1)
`)

	return sb.String()
}
