package reporter

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/bregaldahq/chaossql/internal/domain"
)

// GenerateStandaloneGoRepro generates zero-dependency Go test code (repro_test.go)
// that recreates the schema, runs the minimal operations concurrently in goroutines,
// and asserts the invariant violation.
func GenerateStandaloneGoRepro(spec domain.Spec, ops []domain.ScheduledOp, failingInv *domain.InvariantResult) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by ChaosSQL (github.com/bregaldahq/chaossql). DO NOT EDIT.\n")
	sb.WriteString("// Standalone deterministic reproduction test for detected concurrency anomaly.\n")
	sb.WriteString("package main\n\n")

	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\t\"database/sql\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"log\"\n")
	sb.WriteString("\t\"strconv\"\n")
	sb.WriteString("\t\"strings\"\n")
	sb.WriteString("\t\"sync\"\n")
	sb.WriteString("\t\"testing\"\n")
	sb.WriteString("\t\"time\"\n\n")
	sb.WriteString("\t_ \"modernc.org/sqlite\"\n")
	sb.WriteString(")\n\n")

	// Embed Schema and Seed SQL
	sb.WriteString("// Embedded Schema SQL\n")
	sb.WriteString(formatConstSQL("schemaSQL", spec.Database.Schema))
	sb.WriteString("\n\n")

	sb.WriteString("// Embedded Seed SQL\n")
	sb.WriteString(formatConstSQL("seedSQL", spec.Database.Seed))
	sb.WriteString("\n\n")

	// Define Op Structs
	sb.WriteString(`type stepDef struct {
	sql     string
	capture string
}

type opDef struct {
	id     int
	name   string
	params map[string]string
	steps  []stepDef
}

`)

	// Emit Minimal Operations
	sb.WriteString("var minimalOps = []opDef{\n")
	for _, op := range ops {
		sb.WriteString(fmt.Sprintf("\t{\n\t\tid: %d,\n\t\tname: %q,\n\t\tparams: map[string]string{\n", op.ID, op.Name))
		for k, v := range op.Params {
			sb.WriteString(fmt.Sprintf("\t\t\t%q: %q,\n", k, v))
		}
		sb.WriteString("\t\t},\n\t\tsteps: []stepDef{\n")
		for _, s := range op.Steps {
			sb.WriteString(fmt.Sprintf("\t\t\t{sql: %q, capture: %q},\n", s.SQL, s.Capture))
		}
		sb.WriteString("\t\t},\n\t},\n")
	}
	sb.WriteString("}\n\n")

	// Embed invariant query details
	invName := "anomaly_invariant"
	invQuery := ""
	invAssert := ""
	if failingInv != nil {
		invName = failingInv.Name
		invAssert = failingInv.Expression
		for _, inv := range spec.Invariants {
			if inv.Name == failingInv.Name {
				invQuery = inv.Query
				break
			}
		}
	}
	if invQuery == "" && len(spec.Invariants) > 0 {
		invName = spec.Invariants[0].Name
		invQuery = spec.Invariants[0].Query
		invAssert = spec.Invariants[0].Assert
	}

	sb.WriteString(fmt.Sprintf("const invariantName = %q\n", invName))
	sb.WriteString(fmt.Sprintf("const invariantQuery = %q\n", invQuery))
	sb.WriteString(fmt.Sprintf("const invariantAssert = %q\n\n", invAssert))

	// Helpers: substituteParams, evalSimpleArithmetic, executeOp, evalAssert
	sb.WriteString(`func evalSimpleArithmetic(expr string) string {
	expr = strings.TrimSpace(expr)
	if strings.Contains(expr, "-") {
		parts := strings.Split(expr, "-")
		if len(parts) == 2 {
			a, e1 := strconv.Atoi(strings.TrimSpace(parts[0]))
			b, e2 := strconv.Atoi(strings.TrimSpace(parts[1]))
			if e1 == nil && e2 == nil {
				return strconv.Itoa(a - b)
			}
		}
	}
	if strings.Contains(expr, "+") {
		parts := strings.Split(expr, "+")
		if len(parts) == 2 {
			a, e1 := strconv.Atoi(strings.TrimSpace(parts[0]))
			b, e2 := strconv.Atoi(strings.TrimSpace(parts[1]))
			if e1 == nil && e2 == nil {
				return strconv.Itoa(a + b)
			}
		}
	}
	return expr
}

func substituteParams(sql string, state map[string]string) string {
	result := sql
	for k, v := range state {
		result = strings.ReplaceAll(result, "{"+k+"}", v)
	}
	for strings.Contains(result, "{") && strings.Contains(result, "}") {
		start := strings.Index(result, "{")
		end := strings.Index(result, "}")
		if end <= start {
			break
		}
		expr := result[start+1 : end]
		for k, v := range state {
			expr = strings.ReplaceAll(expr, k, v)
		}
		valStr := evalSimpleArithmetic(expr)
		result = result[0:start] + valStr + result[end+1:]
	}
	return result
}

func executeOp(ctx context.Context, db *sql.DB, op opDef) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin failed: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	localState := make(map[string]string)
	for k, v := range op.params {
		localState[k] = v
	}

	for _, step := range op.steps {
		stmt := substituteParams(step.sql, localState)
		if step.capture != "" {
			var capturedVal interface{}
			row := tx.QueryRowContext(ctx, stmt)
			if err := row.Scan(&capturedVal); err != nil {
				return fmt.Errorf("capture failed on query %q: %w", stmt, err)
			}
			localState[step.capture] = fmt.Sprintf("%v", capturedVal)
		} else {
			if _, err := tx.ExecContext(ctx, stmt); err != nil {
				return fmt.Errorf("exec failed on query %q: %w", stmt, err)
			}
		}
	}

	return tx.Commit()
}

func evalConditionClause(clause string, state map[string]interface{}) bool {
	clause = strings.TrimSpace(clause)
	for k, v := range state {
		clause = strings.ReplaceAll(clause, k, fmt.Sprintf("%v", v))
	}
	
	// Support ==, !=, >=, <=, >, <
	if strings.Contains(clause, "==") {
		parts := strings.Split(clause, "==")
		if len(parts) == 2 {
			l := strings.TrimSpace(evalSimpleArithmetic(parts[0]))
			r := strings.TrimSpace(evalSimpleArithmetic(parts[1]))
			return l == r
		}
	}
	if strings.Contains(clause, "!=") {
		parts := strings.Split(clause, "!=")
		if len(parts) == 2 {
			l := strings.TrimSpace(evalSimpleArithmetic(parts[0]))
			r := strings.TrimSpace(evalSimpleArithmetic(parts[1]))
			return l != r
		}
	}
	if strings.Contains(clause, ">=") {
		parts := strings.Split(clause, ">=")
		if len(parts) == 2 {
			a, _ := strconv.Atoi(strings.TrimSpace(evalSimpleArithmetic(parts[0])))
			b, _ := strconv.Atoi(strings.TrimSpace(evalSimpleArithmetic(parts[1])))
			return a >= b
		}
	}
	if strings.Contains(clause, "<=") {
		parts := strings.Split(clause, "<=")
		if len(parts) == 2 {
			a, _ := strconv.Atoi(strings.TrimSpace(evalSimpleArithmetic(parts[0])))
			b, _ := strconv.Atoi(strings.TrimSpace(evalSimpleArithmetic(parts[1])))
			return a <= b
		}
	}
	if strings.Contains(clause, ">") {
		parts := strings.Split(clause, ">")
		if len(parts) == 2 {
			a, _ := strconv.Atoi(strings.TrimSpace(evalSimpleArithmetic(parts[0])))
			b, _ := strconv.Atoi(strings.TrimSpace(evalSimpleArithmetic(parts[1])))
			return a > b
		}
	}
	if strings.Contains(clause, "<") {
		parts := strings.Split(clause, "<")
		if len(parts) == 2 {
			a, _ := strconv.Atoi(strings.TrimSpace(evalSimpleArithmetic(parts[0])))
			b, _ := strconv.Atoi(strings.TrimSpace(evalSimpleArithmetic(parts[1])))
			return a < b
		}
	}
	return true
}

func evaluateAssertExpression(assertExpr string, state map[string]interface{}) bool {
	clauses := strings.Split(assertExpr, " and ")
	for _, c := range clauses {
		if !evalConditionClause(c, state) {
			return false
		}
	}
	return true
}

func runRepro() error {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	db, err := sql.Open("sqlite", "file:repro_mem?mode=memory&cache=shared")
	if err != nil {
		return fmt.Errorf("failed to open database: %w", err)
	}
	defer db.Close()

	db.SetMaxOpenConns(50)
	db.SetMaxIdleConns(50)

	if schemaSQL != "" {
		if _, err := db.ExecContext(ctx, schemaSQL); err != nil {
			return fmt.Errorf("schema execution failed: %w", err)
		}
	}

	if seedSQL != "" {
		if _, err := db.ExecContext(ctx, seedSQL); err != nil {
			return fmt.Errorf("seed execution failed: %w", err)
		}
	}

	var wg sync.WaitGroup
	for _, op := range minimalOps {
		wg.Add(1)
		go func(op opDef) {
			defer wg.Done()
			_ = executeOp(ctx, db, op)
		}(op)
	}

	wg.Wait()

	if invariantQuery != "" {
		rows, err := db.QueryContext(ctx, invariantQuery)
		if err != nil {
			return fmt.Errorf("invariant query execution failed: %w", err)
		}
		defer rows.Close()

		cols, err := rows.Columns()
		if err != nil {
			return fmt.Errorf("column scan failed: %w", err)
		}

		if rows.Next() {
			values := make([]interface{}, len(cols))
			valuePtrs := make([]interface{}, len(cols))
			for i := range cols {
				valuePtrs[i] = &values[i]
			}
			if err := rows.Scan(valuePtrs...); err != nil {
				return fmt.Errorf("row scan failed: %w", err)
			}

			actualMap := make(map[string]interface{})
			for i, col := range cols {
				var val interface{} = values[i]
				if b, ok := val.([]byte); ok {
					val = string(b)
				}
				actualMap[col] = val
			}

			if invariantAssert != "" && !evaluateAssertExpression(invariantAssert, actualMap) {
				return fmt.Errorf("REPRODUCED ANOMALY: Invariant '%s' violated! Assertion: (%s), State: %v", invariantName, invariantAssert, actualMap)
			}
			fmt.Printf("Invariant '%s' verified with DB state: %v\n", invariantName, actualMap)
		}
	}

	return nil
}

// TestReproduceAnomaly reproduces the minimal concurrency anomaly trace.
func TestReproduceAnomaly(t *testing.T) {
	if err := runRepro(); err != nil {
		t.Errorf("Reproduction assertion: %v", err)
	}
}

func main() {
	fmt.Println("ChaosSQL Standalone Anomaly Reproducer")
	if err := runRepro(); err != nil {
		log.Fatalf("%v", err)
	}
	fmt.Println("Reproduction finished without detected anomaly.")
}
`)

	return sb.String()
}

func formatConstSQL(name, sql string) string {
	if !strings.Contains(sql, "`") {
		return fmt.Sprintf("const %s = `\n%s\n`", name, strings.TrimSpace(sql))
	}
	return fmt.Sprintf("const %s = %s", name, strconv.Quote(strings.TrimSpace(sql)))
}
