// Recorded engine runs used by the landing animations. Generated by
// `node tools/export_site_traces.mjs` from examples/ (never edit by hand).
import banking from './traces/banking_lost_update.json';
import inventory from './traces/inventory_oversell.json';
import hospital from './traces/hospital_write_skew.json';

export interface TraceEvent {
  worker: number;
  op: number;
  type: 'BEGIN' | 'EXEC' | 'COMMIT' | 'ROLLBACK';
  sql: string;
}

export interface RecordedRun {
  scenario: string;
  source: string;
  engineVersion: string;
  driver: string;
  isolation: string;
  seed: number;
  status: string;
  anomalyType: string;
  invariant: { name: string | null; expression: string | null; actual: Record<string, unknown> };
  shrink: { originalOps: number; minimalOps: number; reductionPct: number; trials: number; durationMs: number };
  rawOps: Array<{ id: number; worker: number }>;
  minimalOps: Array<{ id: number; name: string; params: Record<string, string> }>;
  minimalTrace: TraceEvent[];
}

export const RECORDED_RUNS = {
  banking: banking as RecordedRun,
  inventory: inventory as RecordedRun,
  hospital: hospital as RecordedRun,
} as const;

export type RecordedScenario = keyof typeof RECORDED_RUNS;
