apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaossql-server.fullname" . }}-secrets
  labels:
    {{- include "chaossql-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  CHAOSSQL_ADMIN_TOKEN: {{ .Values.secrets.adminToken | quote }}
  {{- if .Values.secrets.discordWebhookUrl }}
  DISCORD_WEBHOOK_URL: {{ .Values.secrets.discordWebhookUrl | quote }}
  {{- end }}
