CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY,
    holder TEXT NOT NULL,
    balance NUMERIC NOT NULL CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS ledger (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id INTEGER NOT NULL REFERENCES accounts(id),
    amount NUMERIC NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
