apiVersion: v2
name: chaossql-server
description: Official Helm chart for ChaosSQL SaaS Control Plane & Concurrency Observability Gate
type: application
version: 1.6.0
appVersion: "1.6.0"
keywords:
  - chaossql
  - database
  - concurrency
  - isolation
  - testing
home: https://chaossql.bregalda.com
sources:
  - https://github.com/bregaldahq/chaossql
maintainers:
  - name: Bregalda Studio
    email: contact@bregalda.com
